services:
  # Database Service
  postgres:
    image: 'postgres:17-alpine'
    container_name: market_viewer_db
    # This automatically injects POSTGRES_USER, POSTGRES_PASSWORD, etc.
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - global-web

  # Application Service
  market-viewer-app:
    build: .
    image: market-viewer:v1
    container_name: market_viewer_app
    depends_on:
      postgres:
        condition: service_healthy
    # Load the same .env file here!
    env_file: .env
    environment:
      # We still need to map the generic Postgres vars to Spring Boot specific vars
      - SPRING_DATASOURCE_URL=jdbc:postgresql://market_viewer_db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      # dont start the development database
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    networks:
      - global-web


networks:
  global-web:
    external: true

volumes:
  db_data: