spring.application.name=market_viewer_app

spring.docker.compose.file=docker-compose-dev.yml
server.servlet.contextPath=/api

# spring/java setup
spring.threads.virtual.enabled=true

# JPA/Hibernate configuraion
spring.datasource.url=jdbc:postgresql://localhost:5433/market_viewer
spring.datasource.username=local_dev
spring.datasource.password=pwd123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#error handling
spring.web.error.include-stacktrace=${SHOW_ERROR_TRACE:always}

#encyption
app.encrypt.password=${ENCRYPT_PASSWORD}
app.encrypt.salt=${ENCRYPT_SALT}

#other values
app.ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

#for early development only
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

