spring.application.name=market_viewer_app

spring.docker.compose.file=docker-compose-dev.yml
server.servlet.contextPath=/api

# spring/java setup
spring.threads.virtual.enabled=true

# JPA/Hibernate configuraion
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#postgresql database setup
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#github sso
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user

#error handling
spring.web.error.include-stacktrace=${SHOW_ERROR_TRACE:always}

#encyption
app.encrypt.password=${ENCRYPT_PASSWORD}
app.encrypt.salt=${ENCRYPT_SALT}

#security
app.cors.deploy-environment=${DEPLOY_ENVIROMENT:local}
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:3000}

#other values
app.ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

#for early development only
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

